import os
import re
from bs4 import BeautifulSoup

def clean_sec_html(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        html_content = f.read()
    
    # Use BeautifulSoup to strip out noisy scripts, CSS styles, and tables
    soup = BeautifulSoup(html_content, "html.parser")
    for section in soup(["script", "style", "table"]):
        section.decompose()
        
    text = soup.get_text(separator="\n")
    # Clean up excess whitespace and blank lines
    text = re.sub(r'\n\s*\n', '\n', text)
    
    # Find the 'Item 1A' section using standard regex mapping for SEC documents
    # SEC filings usually label this as "Item 1A. Risk Factors"
    start_match = re.search(r"Item\s+1A\.?\s+Risk\s+Factors", text, re.IGNORECASE)
    end_match = re.search(r"Item\s+1B\.?\s+Unresolved\s+Staff\s+Comments", text, re.IGNORECASE)
    
    if start_match:
        start_idx = start_match.start()
        # If Item 1B isn't found, capture 100,000 characters after Item 1A
        end_idx = end_match.start() if end_match else start_idx + 100000
        return text[start_idx:end_idx]
    
    return "Could not isolate Item 1A cleanly."

# Walk through the downloaded SEC folder structure to find the raw HTML text files
sec_folder = "sec-edgar-filings"
output_folder = "cleaned_data"
os.makedirs(output_folder, exist_ok=True)

if os.path.exists(sec_folder):
    for ticker in os.listdir(sec_folder):
        ticker_path = os.path.join(sec_folder, ticker, "10-K")
        if os.path.exists(ticker_path):
            # Look inside the submission ID folder generated by the SEC downloader
            for submission in os.listdir(ticker_path):
                full_path = os.path.join(ticker_path, submission, "full-submission.txt")
                if os.path.exists(full_path):
                    print(f"Extracting Risk Factors for {ticker}...")
                    cleaned_text = clean_sec_html(full_path)
                    
                    # Save the clean txt file
                    output_file = os.path.join(output_folder, f"{ticker}_risks.txt")
                    with open(output_file, "w", encoding="utf-8") as out:
                        out.write(cleaned_text)
    print("\nData extraction complete! Look inside your 'cleaned_data' folder.")
else:
    print("Please run download_data.py first to fetch files.")
